language: node_js
node_js:
  - lts/*

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

branches:
  only:
    - master
    - tests

before_script:
  - npm i -g firebase-tools
  - npm i -g @angular/cli
  - npm start -- --silent &

script:
  - npm run cypress:run
  - npm run build:prod

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
